### ISSUE TITLE
Murloc spawns to close together

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#10]
Zone: Darkshore
Area: Twilight Shore
Location: 36, 75
Mob: Greymist Hunter, Greymist Warrior
Error: These mobs' spawn points are so close that pulling one pulls 4-6.  Making quest "Wanted: Murkdeep" almost impossible for two players, unless tank/healer combination.

**Comment by Cillez** [comment]
Issue resolved. Now pulling max 2 creature.
