### ISSUE TITLE
Seal of Command icd

### ISSUE THREAD

**Issue by Juckiey** [renegadewow/Renegade-WoW#101]
Seal of Command currently has a 0.8~ second internal cooldown from proccing, meaning if an ability (crusader strike and divine storm) lines up with an auto swing it will only proc once. This also affects reckoning and other extra swing items such as Hand of Justice and Ironfoe. Its a common bug on most servers, and there isnt any documentation of it ever existing on retail.

Bug report from Dalaran-wow : dalaranwow/dalaran-wow#3351

**Comment by Cillez** [comment]
resolved
