### ISSUE TITLE
Molten Core/BRM Window

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#102]
Description:
Molten Core alternate entrance teleports you outside of the real instance portal within BRD.

Current behaviour:
Currently, when you walk through the "instance portal window" to enter molten core, you enter Blackrock Depths.

Expected behaviour Please include links to your source (for ex. wowhead.com):
You should get teleported directly into the instance.

Steps to reproduce the problem:
Enter the window

Useful links (ex; youtube.com): 
https://i.gyazo.com/7025abe99fb25b5f484ed925b8bb9ab3.png
https://i.gyazo.com/ad9b9cfa4acff518f10f5da1a1ea6882.jpg
https://gyazo.com/359af709d45b4c2b7dc2f8a3c9388add

**Comment by Cillez** [comment]
This was intended. Was done to block of moltencore, but considering we're testing MC on friday, we decided to let it be. 

This will be reverted on release.
