### ISSUE TITLE
Ancient Core Hound Spells

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#103]
Description:
Ancient Core Hound should only cast one spell of his table of possible spells. It should change each lockout. 

Current behaviour:
Currently, Ancient Core Hound can cast all of his possible spells from this table. This should not be the case.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Each different Ancient Core Hound should have a single different spell that they cast. Currently, it casts anything on its possible spell table. http://www.wowhead.com/npc=11673/ancient-core-hound#abilities

**Comment by Cillez** [comment]
resolved.
