### ISSUE TITLE
Baron Geddon Patrol

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#104]
Description:
A common Trinity Core issue is that Baron Geddon will not begin to patrol until a player moves up to a certain point in the room. 

Expected behaviour Please include links to your source (for ex. wowhead.com):
What should happen is that he is always patrolling. There shouldn't be anything that triggers his movement.

**Comment by renegadewow** [comment]
Boss seems to be patrolling fine
