### ISSUE TITLE
UBRS - Dragonspire Door

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#105]
Description:
Dragonspire door should remain closed unless someone has the Seal of Ascension equiped.

Current behaviour:
The door is never closed, players can enter any time.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Door should be closed unless someone has the Seal of Ascension

Useful links (ex; youtube.com): 
http://wowwiki.wikia.com/wiki/Seal_of_Ascension

**Comment by PrinceMonsterTruck** [comment]
The quest is currently bugged, Emberstrife doesn't force the ring

**Comment by renegadewow** [comment]
Using the link provided as reference, the first sentence says "The Seal of Ascension is a ring with several abilities that is obtained through a quest. It is no longer required for access to the upper portion of Blackrock Spire (BRS)"
