### ISSUE TITLE
UBRS - The Beast RP Event

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#107]
Description:
There are a few orcs which should be corpses on the ground/engaged in combat against the Beast.

Current behaviour:
The orcs are always neutral to the beast and not attacking him.

Useful links (ex; youtube.com): 
https://i.gyazo.com/d1ee093d78e8006fd92eb5c8d4d1616b.png

**Comment by Cillez** [comment]
Resolved.
