### ISSUE TITLE
DMN - Quest: A Broken Trap

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#109]
Description:
Quest places a trap when completed, allowing you to freeze Guard Slip'kik.

Current behaviour:
Currently, the trap spawns but Guard Slip'kik does not get frozen by the trap, instead he changes his patrol route to only be three different points.

http://wowwiki.wikia.com/wiki/Quest%3AA_Broken_Trap
http://wowwiki.wikia.com/wiki/Guard_Slip%27kik
https://i.gyazo.com/35bdd68d5c8678c6ce79fad084c2fb78.mp4

**Comment by Cillez** [comment]
Unable to test this as i dont have necessary tools at this moment. Can you take a look? Should be able to make it cast freezing trap when something is in range of it, and then link that event to quest complete. 
@renegadewow can you take a look?

**Comment by renegadewow** [comment]
Resolved, will be applied on next server restart
