### ISSUE TITLE
Stratholme - Trap Portcullis

### ISSUE THREAD

**Issue by metapaws** [renegadewow/Renegade-WoW#110]
Description:
Upon entering certain Portcullis "gated" areas in Stratholme, the gates should close and many small mobs such as rats, maggots, or roaches should spawn and attack the players. The gate should open when these mobs are killed.

Current behaviour:
Nothing happens as you pass through the gates.

https://i.gyazo.com/faf2ff5d76294b96b1528822856a7180.jpg

**Comment by PrinceMonsterTruck** [comment]
The Trigger is spawned, but it doesn't seem to be hooked to the spawn script at the moment.  I'm looking into it

**Comment by Cillez** [comment]
@HeathcliffWoW What was the result after looking into it?

**Comment by Cillez** [comment]
Doors now closes, missing spawning of creatures.

**Comment by Cillez** [comment]
Resolved
