### ISSUE TITLE
Mage:  'Missile Barrage' should be consumed when 'Arcane Missiles' is casted

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#114]
Talent 'Missile Barrage' buff should be consumed by basic spell Arcane Missiles **At the start of channel** when casted, but is not consumed at all.  Can spam Arcane Missiles continually (like 4-6 times) until buff falls off.

1.  Cast arcane blast until you get Missile Barrage talent proc.
2.  Start casting Arcane Missiles (dont use rank 1-3 as they have faster cast times...or you could...i guess)
3.  Keep casting Arcane Missiles and notice the damage stream is not slowing down.
4.  ??????
5. Arcane still not viable lulz

**Comment by dreadnought101** [comment]
Here is a guide on retail that shows how missile barrage is consumed.
https://www.youtube.com/watch?v=eLe1GacBNsk&t=504

**Comment by dreadnought101** [comment]
Another source of an arcane mage, as you can see at the bottom missile barrage is consumed on cast
https://www.youtube.com/watch?v=2yS_fC9ti9w

**Comment by renegadewow** [comment]
Resolved
