### ISSUE TITLE
Winterspring - NPC: Rabid Shardtooth

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#116]
Casts debuff Ability Rabies.

Debuff shows as buff, and cant click it off, or cleanse it normally.

**Comment by Cillez** [comment]
Not following bugtracker template.

**Comment by dreadnought101** [comment]
Fine then, i guess will ignore this bug since it didn't follow the template exactly despite giving enough details and another GM confirmed it and stream evidence showed the bug at the time.

Heres the stream, Timestamp 7 minutes 3 seconds https://www.twitch.tv/videos/259072987

**Comment by Cillez** [comment]
Fixed.
