### ISSUE TITLE
Buffs are retained after switching specs

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#118]
For example, casting Blessing of Sanctuary, then switching to a different spec that has no blessing of sanctuary talented will still keep that buff on targets.

Normally all buffs are removed when switching specs.

**Comment by Cillez** [comment]
Any source to back this up? I've checked some of the servers known for great scripting and they seem to have the same 'problem'. I've also taken the time to search their bugtracker for similar reported bugs but can't seem to find anything.
