### ISSUE TITLE
Shaman Tier 2.5 

### ISSUE THREAD

**Issue by AvatarRoku112** [renegadewow/Renegade-WoW#122]
The 3 set Chance on cast 20% of Lightning Bolt, Chain Lightning, and shock spells does not work.

**Comment by HeathcliffWoW** [comment]
Could you please be more specific on how it doesn’t work?

**Comment by RenegadeWoW-CrazyJ** [comment]
Thank you for the report, but please open a new ticket following the template to provide more information.
