### ISSUE TITLE
Tender and Tender Ferals are passive from the starting Blood Elves zone.

### ISSUE THREAD

**Issue by naitguolf** [renegadewow/Renegade-WoW#123]
Description:
Tender and Tender Ferals are passive from the starting Blood Elves zone.

Current behaviour:
Tender and Tender Ferals are passive from the starting Blood Elves zone.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Tender and Tender Ferals should be aggresive as in the original game.

Steps to reproduce the problem:
Create a blood elf.
Go to the south, you will bee Tender and Tender Feral neutral, should be aggresive.

**Comment by Cillez** [comment]
resolved.
