### ISSUE TITLE
Torches in BRD

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#125]
Description:
Shadowforge Torches in BRD dont work as they should

Current behaviour:
If you right click the torch you can use ut on the Brazier from as far away as you want

Expected behaviour 
Should have a max range ( melee range i think)

Steps to reproduce the problem:
1. Get into BRD up until the room with all the small nonelites where you have to light the braziers in order to open the door
2. Kill a Flame Keeper to obtain a torch
3. Right click the torch then left click the brazier

**Comment by renegadewow** [comment]
Will be applied on next server restart.
