### ISSUE TITLE
BRD Door in Torch Room

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#126]
Description:
The doors in Torch room dobt behave like they should

Current behaviour:
Lighting one brazier opens one of the doors

Expected Behavior
Lighting one brazier shouldnt have any effect.
Lighting both opens both doors

Steps to reproduce the problem:
1. Get into torch room
2. obtain torch
3. light one brazier

Useful links (ex; youtube.com):

**Comment by RenegadeWoW-CrazyJ** [comment]
This issue has been resolved, and will be available with the next build.
