### ISSUE TITLE
Golemlord Argelmach

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#128]
Description:
Golemlord Argelmach doesnt pull the entire room uppon being attacked

Current behaviour:
"

Expected behaviour 
Golemlord should pull everything in his room upon being attacked

Steps to reproduce the problem:
1. Go to Golemlord
2. Whack him
3. observe that nothing happens

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
