### ISSUE TITLE
Stratholme Gates

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#130]
Description:
If you enter stratholme at main entrance take the first turn left and then look to the right there is a gate. This gate is supposed to have a scripted event if you step inside

Current behaviour:
Stepping inside, nothing happens

Expected behaviour 
If you walk in there, both the Gates should close and there are a lot of maggots / rats spawning.
The gates would stay closed until either all the mobs die, or the players inside died

Steps to reproduce the problem:
1. Get to stratholme
2. Make Sense of my terrible description of where the fucking gate is
3. Go to the gate and step under it

Useful links (ex; youtube.com):

**Comment by RenegadeWoW-CrazyJ** [comment]
#110 Report already exist. Closing because: Duplicate.
