### ISSUE TITLE
Baroness Anastari not using possess

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#131]
Description
Missing Boss Ability

Current behaviour:
3 man'd her, took a long time, didnt cast her possess ability even once

Expected behaviour 
Should use https://wotlk.evowow.com/?spell=17244

Steps to reproduce the problem:
1. Go to strat
2. Fite her

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
