### ISSUE TITLE
Force Reactive Disk doesn't proc properly after death

### ISSUE THREAD

**Issue by Drakefood** [renegadewow/Renegade-WoW#133]
Description:
After dying and resurrecting Force Reactive Disk (ID:18168) does not proc as intended until you take off and equip it again.

Current behaviour:
After dying the 'when the shield blocks' effect does not activate

Expected behaviour Please include links to your source (for ex. wowhead.com):
http://www.wowhead.com/spell=22618/force-reactive-disk should still activate after dying and resurrecting 

Steps to reproduce the problem:
1. Equip http://www.wowhead.com/item=18168/force-reactive-disk
2. fight an enemy and block their attacks (using a block rating increasing ability such as warrior's 'Shield Block' makes this easy to reproduce). The blocks should cause your character to damage the surrounding enemies with lightning 
3. Kill your character
4. Resurrect your character 
5. Reproduce Step 2

Useful links (ex; youtube.com): 
https://puu.sh/AkLcP/a950dac38a.png (Force Reactive Disk triggering in the same way as Thorium Shield Spike)
https://puu.sh/AkLdd/365bc0b37c.png (After death: Force Reactive Disk no longer triggering)

**Comment by renegadewow** [comment]
Resolved, will be applied on next restart.
