### ISSUE TITLE
DM-W pylons moot

### ISSUE THREAD

**Issue by saxproxy** [renegadewow/Renegade-WoW#136]
Description:
The final boss is unlocked from the start of the dungeon, clearing the mobs around the pylons is not necessary

Current behaviour:
You can skip the trash and go straight to the boss via library or with a rogue lock pick from the west

Expected Behaviour:
Boss should be sealed behind a magic barrior, only able to be passed after clearing the 5 pylons throughout the instance.

Scource: 
http://www.tentonhammer.com/guides/dire-maul-west

Steps to reproduce the problem:
1. Enter Dire Maul West
2. Skip trash
3. Wrek boss

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
