### ISSUE TITLE
DM-W Illyanna Ravenoak missing pet

### ISSUE THREAD

**Issue by saxproxy** [renegadewow/Renegade-WoW#137]
Description:
Illyanna Ravenoak missing pet bear

Current behaviour:
Boss mob has No pet

Expected behaviour:
She should have a pet bear

Source: 
https://www.almarsguides.com/wow/instances/dmwest.cfm

Steps to reproduce the problem:
1. Enter Dire Maul West
2. Go up stairs
3. Illyanna is alone

Useful link:
https://m.youtube.com/watch?v=VyQMDWMsOWI

**Comment by Cillez** [comment]
Resolved.
