### ISSUE TITLE
DM-W warlock Mount quest permanent spawn

### ISSUE THREAD

**Issue by saxproxy** [renegadewow/Renegade-WoW#138]
Description:
The warlock class quest for the mount is enabled for everyone in the dungeon every time, even without a warlock in the group

Current behaviour:
In the final boss room, warlock class quest boss is spawned

Expected behaviour:
Boss should only spawn when warlock initiates the quest after meeting the quest prerequisites.

 Source: http://www.wowhead.com/forums&topic=7114/how-to-get-your-warlock-epic-mount-a-guide

Steps to reproduce the problem:
1. Enter DIre Maul West
2. Go to final boss room
3. Encounter http://www.wowhead.com/?npc=14506

**Comment by ForsenGM** [comment]
Since I tested this myself, I can confirm this report.
