### ISSUE TITLE
Shaman spell icons

### ISSUE THREAD

**Issue by Thraxxia** [renegadewow/Renegade-WoW#140]
Description:
Call of the elements and Totemic Recall have wrong icons. Instead of their default icons they have the icons of druid shapeshifting.
Current behaviour:
Not much. The funcionality is unchanged, only icons
Expected behaviour Please include links to your source (for ex. wowhead.com):
Should look differently
Steps to reproduce the problem:
Create a shaman character

Useful links (ex; youtube.com):

**Comment by Thraxxia** [comment]
Resloved by deleting cache

**Comment by renegadewow** [comment]
Resolved, cache issue
