### ISSUE TITLE
Scholomance Item duplicate loot

### ISSUE THREAD

**Issue by Taemeluch** [renegadewow/Renegade-WoW#143]
Description:
Looted a Orb of Deception and got 11 of them

Current behaviour:
Looting an item seems to give more than one with blue items in scholomance

Expected behaviour Please include links to your source (for ex. wowhead.com):
Should only be one item

Steps to reproduce the problem:
1. Killed a mob
2. Hit need on item
3. Got 11 of them

Useful links (ex; youtube.com):

**Comment by ForsenGM** [comment]
Tried it, doesn't seem to do anything unusual. I feel like this bug report is not correct.
