### ISSUE TITLE
Warrior Bloodsurge Talent

### ISSUE THREAD

**Issue by AvatarRoku112** [renegadewow/Renegade-WoW#144]
Description:
Bloodsurge active causes the Slam spell to have no cast time. The talent properly reduces the cast time, however using Slam does not get rid of the Bloodsurge proc. So you can effectively use Slam 3-4 times every Bloodsurge proc.

Current behaviour:
Bloodsurge not being used up when Slam is used.

Expected behaviour:
Bloodsurge should only remove the cast time of 1 Slam, as stated in the text of the talent "making your next Slam instant."

**Comment by renegadewow** [comment]
Resolved.
