### ISSUE TITLE
Kirtonos the Herald bugs

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#145]
Description:
-Kirtonos the Herald (Second boss in Scholomance) does not spawn properly.
-The gate is not lowered when you try to summon him, and the flight path/animation he uses before he 

**Current behaviour:**
Does not properly fly/animate (which normally lasts around 30 seconds)
Does not spawn in middle of room (we think he spawns outside the instance)

**Expected behaviour Please include links to your source** 
Flies outside the window when you activate the fire pit [Trigger works properly here] and takes around a minute before he lands in the center of the room and becomes targetable.
Retail Version test run - 
https://www.youtube.com/watch?v=VAWFsYprkhk

Steps to reproduce the problem:
1.   Use Blood of Heroes [ID: 12938] and click Brazier of the Herald
2.  Watch outside as a Gargoyle paths along a small around hill down to the left outside the window
3.  ????? 

(After notes:  If Kirtonos spawns properly, and wipes group, he needs to despawn, gate raises, and the brazier needs to be targetable again to try to summon him again)

**Comment by Cillez** [comment]
Resolved.
