### ISSUE TITLE
Missile Barrage talent is appearing as debuff

### ISSUE THREAD

**Issue by pakicar** [renegadewow/Renegade-WoW#146]
Description:
Missile Barrage is a proc that Arcane mages have and its one of the key talents in they tree and rotation.
Current behaviour:
When Missile Barrage procs it will appear in debuff slots, right next to Arcane Blast debuff.
It has no impact on the gameplay, its more like aesthetic issue.

Expected behaviour Please include links to your source (for ex. wowhead.com):
It will appear in buffs slots, already checked on two private servers and it had always appeared in buffs.
Link: http://wowwiki.wikia.com/wiki/Missile_Barrage

Steps to reproduce the problem:
1. Get talent Missile Barrage in Arcane tree.
2. Cast Arcane Blast until you get the proc.
3. Missile Barrage will proc as debuff.

Useful links (ex; youtube.com): 
https://www.youtube.com/watch?v=fCkvcedqPuU
You can see in first 20 seconds of the video Missile Barrage proc.

**Comment by Cillez** [comment]
We are aware of the issue. Since it is a visual bug it will be low priority.

**Comment by BanjeeWoW** [comment]
its not visual only, missile barrage can be dispelled by pallies and priests

**Comment by Cillez** [comment]
Fixed so it can be dispelled.

**Comment by renegadewow** [comment]
Resolved, will be applied on next server restart.
