### ISSUE TITLE
Risen Lackey's in Scholomance

### ISSUE THREAD

**Issue by AvatarRoku112** [renegadewow/Renegade-WoW#148]
Issue : When wiped in the second room Risen Lackey's will not despawn/reset. When pulling them they pull the caster and adjacent mobs. As well as the spawner of the mobs will continually cast Risen Lackey, which seems to be working, but if you can't keep up with DPS will spawn immeasurable amount of undead skellys.

Fix - despawn Risen Lackeys properly, or somehow fix their aggro from pulling their creator. As well as possibly putting Risen Lackey on a small CD to disrupt the ever constant flow of Risen Lackeys flooding the room.

**Comment by renegadewow** [comment]
Not following template and insufficient info.
