### ISSUE TITLE
Darkmaster Gandling spawning before all minibosses are killed.

### ISSUE THREAD

**Issue by AvatarRoku112** [renegadewow/Renegade-WoW#149]
Issue : Darkmaster Gandling is spawned without killing any of the minibosses, killing him is essentially impossible in it's current state. He will teleport you into the rooms to kill adds, but being there are the bosses themselves and the room's trash, makes it a little difficult to say the least.

Fix - Darkmaster Gandling is only summonable after killing all minibosses, as has always been.

**Comment by Cillez** [comment]
Resolved.
