### ISSUE TITLE
Quest bug still see ?

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#15]
Zone: Teldrassil
Area: Lake Al'Ameth
Location: 60,68
Quest: The Sprouted Fronds (2399)
When you complete the quest, the "?" remains over the plants.  Afterwards, you can interact with the plants and see an NPC dialogue box. "Greetings <playername>"

**Comment by Cillez** [comment]
Working properly when i tested it. Testing on new character.

**Comment by Cillez** [comment]
Bug confirmed. Fixed by making a quest ender point.
