### ISSUE TITLE
Mobs pull through walls

### ISSUE THREAD

**Issue by saxproxy** [renegadewow/Renegade-WoW#150]
Description:
Mobs will path through wall/clipping instead of going around when agro.

Current behaviour:
when kiting mobs around a wall they will instead cut through the wall

Expected behaviour Please include links to your source (for ex. wowhead.com):
Mobs should go around any clipped areas
Source: Anyone who has played WoW

Steps to reproduce the problem:
1. Find a mon near a wall
2. Agro/taunt
3. Go around wall

**Comment by Cillez** [comment]
This is intended while we're investigating another issue being triggered by mob pathing. Mob pathing will be available before release.
