### ISSUE TITLE
Dire Maul West: Lord Hel'nurath

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#152]
Description:
Lord Hel'nurath is spawned right next to Immolthar's prison

Expected behaviour 
He shouldnt be there unless Summoned by someone on the warlock mount quest

Steps to reproduce the problem:
1. Go to DM West
2. Go all the way to Immol'thars Prison
3. He is a big dreadlord accompanied by felguards, shouldnt have issues finding him

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Duplicate
