### ISSUE TITLE
Stratholme: Eye of Naxxramas

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#153]
Description:
There is an issue with the mobs summoned by Eye of Naxxramas

Current behaviour:
If you ignore an eye of naxxramas till it summons mobs, and then kill it when its done summoning, the mobs dissappear with it

Expected Behaviour
Even if the eye dies the mobs shouldnt despawn

Steps to reproduce the problem:
1. Enter stratholme Living 
2. Clear trash until an eye spawns
3. let it summon mobs
4. Kill it

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
