### ISSUE TITLE
Dire Maul East: Isalien and Empyrean

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#157]
Description:
Spawned in DM:E.

Current behaviour:
They are in the same Boss room as Alzzin the Wildshaper

Expected behaviour
They only should spawn after being summoned by someone on the Dungeon Set 2 Quest Chain

Steps to reproduce the problem:
1. Get into Dire Maul East
2. Find Isalien and Empyrean in the final Boss room
Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
