### ISSUE TITLE
Dire Maul West: Ancient Equine Spirit

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#158]
The Ancient Equine Spirit is Part of the Paladin Epic Mount questchain, he is supposed to spawn after the group slays Tendris Warpwood, while a paladin is on the quest "Ancient Equine Spirit"

Steps to reproduce:
1. Enter Dire Maul West
2. Walk towards Tendris Warpwood
3. See him stand next to Old Ironbark

**Comment by Cillez** [comment]
Resolved.
