### ISSUE TITLE
UBRS: Pyroguard Emberseer

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#159]
Description
Scripted Even to make emberseer Spawn is not working

Current behaviour:
If you enter Pyroguard Emberseer's Room, the Blackhand Incarcerators immediately attack you. Also the Door Closes.

Expected behaviour 
Incarcerators should stand in place channeling a blue spell onto Pyroguard.
They are Supposed to be unattackable whild doing that and wont attack the group either. Once someone starts channeling on the altar for a few seconds, they stop channeling themselves and attack the grp.
Pyroguard ( not targetable and small at the start) starts to grow and emotes "Pyroguard Emberseer is nearly at full Strength" and then a few seconds later attacks the group

Steps to reproduce 
1. Enter UBRS
2. Fight your way towards Pyroguard Emberseers Room
3. See what happens when you enter

Useful links (ex; youtube.com):

**Comment by Zvertk69** [comment]
I think it could be linked back to this issue but with the doors closing, I am almost positive when we went in and got trapped it was the reason the door was closed.

**Comment by Cillez** [comment]
Only problem with this room now is that the Incarcerators doesn't channel the blue spell. You can summon the boss fine, aswell as doors open/closes correctly.

**Comment by RenegadeWoW-CrazyJ** [comment]
The npcs will now will cast their channeled spell as well as being immune to player characters until the altar has been clicked. These changes will be available with the next build.
