### ISSUE TITLE
Aggrotable on Certain Mobs

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#161]
Descriptions
Mobs summoned by other mobs, like Risen Lackies in Scholomance and the Water Elementals Summoned by Crimson Conjourors in the Living side of Stratholme seem to just run at the first person that causes any kind of threat without being tauntable or responding to any threat caused by party members.

Expected Behaviour
These "pets" should respond to threat and taunts like any other mob does

Steps to reproduce the problem:
1. Pull for example a Dark Summoner in Scholomance
2. Wait for it to summon a Risen Lacky
3. Try to pull the lacky off whoever he runs after

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Working as intended now.
