### ISSUE TITLE
UBRS General Drakkisath

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#162]
Description
Conflag not being used or not CCing the target

Current behaviour:
Issue might need a little more testing, but as of right now, i know Drakk doesnt CC the target with his conflageration. I have seen servers where Drakk uses the wrong spell ( A Conflag that doesnt CC). However it is possible too, that he doesnt use Conflag at all.

Expected behaviour 
Drakkisath is supposed to Periodicaly Conflagerate the tank.
His Conflageration is Supposed to Desorient the Target for a full 10 seconds, which makes having 2 tanks a must have for him.

Steps to reproduce the problem:
1. Enter UBRS
2. Go to Drakkisath's Room
3. Pull him and look for Conflag

Useful links (ex; youtube.com):

**Comment by Zvertk69** [comment]
I was in the UBRS run and can confirm that conflag is not CCing but it is being used.

**Comment by PrinceMonsterTruck** [comment]
I’ll take a look at his scripting and see what I can find

**Comment by dreadnought101** [comment]
I believe the issue with conflagerate is that it does not disorientate you despite it targetting and dealing damage properly?

**Comment by RenegadeWoW-CrazyJ** [comment]
Cannot replicate this issue.
