### ISSUE TITLE
big arcane mage bug 

### ISSUE THREAD

**Issue by Ryry561** [renegadewow/Renegade-WoW#163]
Description:
When playing arcane mage and using missle barrage talent it doenst use arcane missles at all

Current behaviour:
you go to cast it and it doesnt do anything 

Expected behaviour Please include links to your source (for ex. wowhead.com):
https://youtu.be/ONaeh55uymw?t=1m15s 

Steps to reproduce the problem:
1.  On target dummy take the Missile Barrage talent
2. Cast 4 Arcane blasts Should get missle barrage proc
3. Then cast arcane missiles and nothing happens 

Useful links (ex; youtube.com):

**Comment by renegadewow** [comment]
Invalid
