### ISSUE TITLE
Shaman Flametongue

### ISSUE THREAD

**Issue by AvatarRoku112** [renegadewow/Renegade-WoW#165]
Flametongue weapon used with dual wield is supposed to give spell power from both weapon enhancements but only works for 1.

Earthliving weapon is currently working as intended, giving Healing Power off of both weapon enhancements.

http://wowwiki.wikia.com/wiki/Patch_3.3.5a 
Patch 3.3.5a was introduced June 29, 2010.

http://www.wowhead.com/forums&topic=159303/dual-wielding-do-effects-stack 
My Source was posted June 06, 2010. So some discrepancy may be there.

**Comment by renegadewow** [comment]
Resolved, will be applied on next restart.
