### ISSUE TITLE
Dire Maul West: More obsolete NPCs

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#166]
Description:
Found a few more NPCs that are only supposed to be visible when certain conditions are met
Current behaviour:
Right now there are few NPCs there that are part of the lock Mount quest and should only be visible while doing the quests.
Dreadsteed Spirit, Right next to Immol'thar
Dreadsteed Spirit, Xorothian Imp and a Highborne Summoner at the Pylon North of Immol'thars Prison
There also is an Eye of Immol'thar right next to the three, which is part of Immol'thars Bossfight and should be removed too, as they should only be spawned

Expected behaviour 
Noone of those are supposed to be there

Steps to reproduce the problem:
1. Get to Dire Maul West
2. Enter Immol'thars Prison
3. Observe
Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
