### ISSUE TITLE
Dire Maul North/West

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#167]
Description
There is Supposed to be a Door closing off Dire Maul West.

Current behaviour:
No Door to be found

Expected behaviour:
There is supposed to be a closed Door between the Athanateum and the Hallway towards Immol'thar's Prison, that only opens once Immol'thar dies.

Steps to reproduce the problem:
1. Go to Dire Maul North
2. Enter the Library
3. Go Upstairs and see no door closing off the tunnel

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
