### ISSUE TITLE
Dire Maul West: Prince Tortheldrin

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#168]
Description
Prince Tortheldrin is in the wrong location and always attackable.

Current behaviour:
He stands in the Library Upstairs and is always attackable

Expected behaviour 
He is Supposed to stand downstairs and only be attackable after Immol'thar is dead.

Steps to reproduce the problem:
1. Enter Dire Maul North
2. Enter the Library 
3. Observe

**Comment by Cillez** [comment]
Resolved
