### ISSUE TITLE
Dire Maul East: Old Ironbark and the Door

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#169]
Description:
So, this has been referenced as a side note in a different bugreport, but i thought i'll give some extra detail to it.

Current behaviour:
Currently, if you enter Dire Maul East, just run in a straight line, drop down and turn to the left and you'll be at the final boss within 1 minute of entering the dungeon, in fact you dont have to kill a single trash mob to complete the dungeon.

Expected Behaviour:
Normally, there Should be a door blocking off the direct path to the final boss room. This Door can only be opened by Ironbark. (The big tree dude in the middle of the instance) However he can only do it after Zevrim Thornhoof is dead, because he is cursed by the Satyr. After you kill Zevrim, "Old Ironbark" will turn into "Ironbark the Redeemed" and have a dialog option available that makes him walk towards the door, push it open and die (srsly wtf blizzard, the poor treedude)

Steps to reproduce the problem:
1. Enter Dire Maul East
2. Check the missing Door

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Resolved.
