### ISSUE TITLE
Darnassus Sentinel Hippogryph option marker

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#17]
Zone: Teldrassil
Area: Darnassus
NPC: Darnassus Sentinel
Error: The "Hippogryph Master" option should give a marker at 29,41 to mark the portal.

Suggested fix: Zone: Teldrassil
Area: Darnassus
Using the option "Lexicon of Power" would be nice you give the same coordinates as that of the inscription trainer (59, 14) instead of just "The ancient tomes are always found near inscription trainers.".

**Comment by renegadewow** [comment]
Resolved
