### ISSUE TITLE
Alzzin the Wildshaper

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#170]
Description: Missing Boss mechanic

Current Behaviour:
Currently the path behind him is not blocked and no imps are spawned when he goes below 30%

Expected behaviour 
The pathway behind Alzzin should be blocked at first, when he goes below 30% the wall behind him blasts open, showing the pathway and he spawns some imps (Alzzin's Minion) that start running at the party from out of that pathway.

https://youtu.be/SM5RSImloKw

Steps to reproduce the problem:
1. Enter DM East
2. Make your way to  Alzzin
3. inspect the already opened pathway
4. Fight alzzin, to see no imps are spawned

**Comment by Cillez** [comment]
Couldnt find right object to block the path, so added another door in DM inplace.
