### ISSUE TITLE
Healing Debuff in dungeons

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#172]
Description:
The 25% Healing debuff does not apply to shields
The 25% Healing debuff breaks when you leave dungeon and re-enter it

Current behaviour:
Healing debuff falls of if you use RDF teleport out and in, or mage portal, or simply walking out of dungeon and back in

Expected behaviour Please include links to your source (for ex. wowhead.com):
Should be applied at all times when inside dungeon.
Should be applied to shields/absorbs from warlocks/mages/priests

Steps to reproduce the problem:
1. Outside Dungeon entrance, heal yourself (Druid Regrowth best example as it has both initial and HoT heal)  Enter Dungeon, heal again, notice how it drops.  Exit dungeon and re-enter and notice it NO LONGER drops 25% in healing output.
2. Resetting dungeon instances also resets healing debuff, so when you enter it applies 25% normally as it should.  (but if you leave dungeon and enter the same instance ID, the healing debuff is no longer applied)
3. Healing Debuff functions properly even when players die and ressurected/revived by other players inside instance.
4. Healing Debuff is no longer applied/drops off if you die, release spirit and run back to the instance manually

**Comment by Cillez** [comment]
25% healing debuff was never intended to apply to shields.

**Comment by dreadnought101** [comment]
> 25% healing debuff was never intended to apply to shields.

oh

**Comment by Cillez** [comment]
BUT! that doesnt mean we wont add it :)

**Comment by renegadewow** [comment]
Resolved.
