### ISSUE TITLE
Lower Blackrock Spire Urok Doomhowl

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#176]
Description:
If you summon Urok Doomhowl, the waves of Mobs that spawn before he spawns himself are way to quick to be handled by a low / decently geared group
Current behaviour:
Waves spawn with less than 10 seconds delay between them, each wave consists of 3 elite ogres
Expected behaviour
Slow it down a Little bit,
Steps to reproduce the problem:
1. Enter LBRS
2. Move to Urok's platfrom and start the summon
3.Observe
Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Checked with how it works on retail, timers are really quick there to, ranging from 5-10 seconds. Might need to be nerfed a bit.
