### ISSUE TITLE
BRD: Bridge Ambush

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#178]
Description:
Usually if you cross the middle of the Bridge between the hallway behind the Spectator ranks of the ring of law and the Garrison that leads into the City, 2 Anvilrage Guardsmen are supposed to spawn (1 ahead of you 1 behind you) and attack the group
Current behaviour:
Event not scripted
Expected behaviour
 https://youtu.be/H4D0WOS-hYY?t=17m9s
Steps to reproduce the problem:
1. Enter BRD
2. Use my shitty description to find the Bridge
3. Cross the middle, observe nothing happening

Useful links (ex; youtube.com):

**Comment by Cillez** [comment]
Fixed by Bomber. Available on next restart.
