### ISSUE TITLE
Scarlet Monastery Cathedral - Mograine aggro chain

### ISSUE THREAD

**Issue by Drakefood** [renegadewow/Renegade-WoW#180]
Description:
Mograin aggro should be chained with the trash mobs inside of the Crusader's Chapel inside of SM Cathedral 

Current behaviour:
As the boss is attacked, remaining trash mobs are unaffected 

Expected behaviour Please include links to your source (for ex. wowhead.com):
As the boss is attacked, remaining trash mobs inside of the Chapel (not the entire instance) should enter the combat as well.

Steps to reproduce the problem:
1. Without clearing the chapel, attack Scarlet Commander Mograine

Useful links (ex; youtube.com): 
https://youtu.be/72c8YUNusEo?t=3m10s (As he turns his camera around, you can see how minions on the sides, which are too far to be pulled are entering combat.)

**Comment by renegadewow** [comment]
Resolved, will be applied on next server restart.
