### ISSUE TITLE
Scarlet Monastery Cathedral - Door to Whitemane doesn't reset

### ISSUE THREAD

**Issue by Drakefood** [renegadewow/Renegade-WoW#181]
Description:
After resetting the instance, the door separating the last bosses doesn't reset

Current behaviour:
After resetting the dungeon, the door behind Scarlet Commander Mograine is still open

Expected behaviour Please include links to your source (for ex. wowhead.com):
Before the battle with Mograine, the door behind him should be closed, only to be opened after his death to let High Inquisitor Whitemane into the room.

Steps to reproduce the problem:
1. Enter Scarlet Monastery Cathedral
2. Before killing Mograine, observe that the door behind him is closed
3. Kill Mograine and Whitemane
4. Leave the dungeon and reset instances
5. Enter the dungeon again and observe that the door behind Mograine is now open 

This is mainly a visual issue, but could potentially be abused to attack Whitemane before Mograine

Useful links (ex; youtube.com): 
https://youtu.be/JQbTo9Tbst0?t=41m54s (Door closed before the battle)
https://puu.sh/AntaY/02052f3a7a.jpg (Door open before the battle)

**Comment by HeathcliffWoW** [comment]
I don’t understand how that could happen, unless the “Master” instance (I can’t think of the right word for when it’s edited for everyone) had the door opened by a GM.  I’ll take a look into this

**Comment by RenegadeWoW-CrazyJ** [comment]
Reworked to door to ensure that it will always reset.
