### ISSUE TITLE
[Armory] Firefox display - Broken

### ISSUE THREAD

**Issue by Hodor-Cosmin** [renegadewow/Renegade-WoW#191]
Description:
Item display on hover is incorrect.

Current behaviour:
Upon hovering my mouse over an item, it gets displayed in the left upper corner (or sometimes totally random position) of the browser, while scrolling the item remains in the same position.

Expected behaviour :
Item should be display on mouse hover and while scrolling its should adapt its position or dissapear.

* Red dot indicates my mouse position * 
![image](https://user-images.githubusercontent.com/29095107/40267468-9311f486-5b54-11e8-9b71-2bfc89159a9b.png)

**Comment by Cillez** [comment]
Fixed on next release of website.
