### ISSUE TITLE
Scholomance - Jandice Barov

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#195]
Description:
Jandice Barov boss in Scholomance.  What is working and what is bugged.

Current behaviour:
CORRECT~~
-Casts Curse of Blood
-Casts correct amount of illusions (https://wotlk.evowow.com/?spell=17773) that last 30 seconds

UNSURE~~
-Cant tell if she casts Dark Plague (as the fight never lasted long enough but I assume yes she can)

BUGGED~~
When Jandice Wipes group during split illusion phase, she stays invisible.  (You can still see a book floating around attacking things...)
Minute 59:00 of video - https://www.twitch.tv/videos/265162262  

Expected behaviour Please include links to your source (for ex. wowhead.com):
Shouldn't be a floating book when you die...?  

Steps to reproduce the problem:
1. Engage Jandice Barov
2. When she splits into many illusions, die at that point.
3. (Could also test death after illusions)

Useful links (ex; youtube.com): 
Twitch video, starts at 57 minutes! - https://www.twitch.tv/videos/265162262  
Jandice Barov - https://wotlk.evowow.com/?npc=10503#abilities
Illusion of Jandice Barov - https://wotlk.evowow.com/?npc=11439#summoned-by

**Comment by RenegadeWoW-CrazyJ** [comment]
Cannot reproduce reset issue.
Cannot find 2+ reliable sources to confirm conditions of the "Dark Plague" cast.

**Comment by Cillez** [comment]
Why was this reopened if you can't find reliable sources to confirm the conditions of the dark plague cast?

**Comment by dreadnought101** [comment]
I believe because he was able to reproduce the unatackable flying book Jandice Barov issue.

  The issue was narrower then expected.
Jandice Barov goes invisible for 3 seconds while she spawns adds, previously I thought it was bugged when we wiped at any point during the fight and made jandice untargetable when she reset, but it was actually during those 3 seconds, not after that she bugged out.

**Comment by RenegadeWoW-CrazyJ** [comment]
The reset issue has been fixed and will be available with the next build. Still cannot find good documentation on "Dark Plague". If any is found please open a new ticket with it.
