### ISSUE TITLE
Scholomance - Blood Steward of Kirtonos

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#196]
Description:
The 2 Curses: Curse of Impotence, Curse of Weakness

Current behaviour:
-Only targets target the boss is aggrod to instead of randomly selecting a member of the group
-She seems to cast these curses extremely quickly.  Unsure if blizzlike or not.
(Evasion and Paralyzing Poisen confirmed working properly, Curses also seems to be applying debuffs appropriately )

Expected behaviour Please include links to your source (for ex. wowhead.com):
Curses target random members of group
Im unsure but I feel like she should be cursing less often.

Useful links (ex; youtube.com): 
https://wotlk.evowow.com/?npc=14861
https://www.twitch.tv/videos/265162262  (Blood Steward of Kirtonos at 23:30 minutes)

**Comment by Cillez** [comment]
Resolved.
