### ISSUE TITLE
Core/Scripts - The Balance of Light and Shadow (quest)

### ISSUE THREAD

**Issue by Zvertk69** [renegadewow/Renegade-WoW#198]
Description:
When you accept the quest and then step over to the area to do the quest, the event won't trigger the event that is suppose to take place.

Current behavior:
When you run to/near the area where the trigger is or should be the event will not start.

Expected behavior:
Suppose to be able to get near the cave and the event start and before the peasant's spawn you should be able to see the Scourge archers. (Videos in the links at end of report that show the event)

Link to quest: [https://wotlk.evowow.com/?quest=7622](url)

Steps to reproduce the problem:
1. Talk to Eris Havenfire

- (stationary NPC that attacks during event [Suppose to be un-attackable]) Scourge Archer: [https://wotlk.evowow.com/?npc=14489](url)

- (walk towards light NPC) Plagued Peasant: [https://wotlk.evowow.com/?npc=14485](url)

- (walk towards light NPC) Injured Peasant: [https://wotlk.evowow.com/?npc=14484](url)

- (NPC that attacks during event [Suppose to be attackable]) Scourge Footsoldier <Kel'Thuzad's Minion>: [https://wotlk.evowow.com/?npc=14486](url)

2. Accept the quest The Balance of Light and Shadow
3. Walk over to the area or near and see that the event is not triggered at all.

Useful links (ex; youtube.com): 
[https://www.youtube.com/watch?v=sNNaQRnC1PI](url)
[https://www.youtube.com/watch?v=1hG2m77LRJQ](url)
[https://www.youtube.com/watch?v=z2Ud0n2-BP0](url)

**Comment by RenegadeWoW-CrazyJ** [comment]
This encounter has been scripted and will be available with the next build.
