### ISSUE TITLE
Stormwind Guard patrol pathing issues

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#20]
Zone: Elwynn Forest
Area: Elwynn Forest
NPC: Stormind Guard
This NPC patrols from Northshire Valley to Goldshire.  After aggroing a mob, and defeating the mob, NPC begins falling through the map or walking through trees.  This happens periodically, steady watching this NPC will eventually recreate the error.

**Comment by renegadewow** [comment]
Fixed
