### ISSUE TITLE
MOUNT BUG IN DUN MOROGH cords 71.4 50.2

### ISSUE THREAD

**Issue by yeetmaster52** [renegadewow/Renegade-WoW#200]
Description:
CHANGEME Description of the problem or issue here.
when you run off the a little bit you get dismounted and when you try to remount it says your inside
Current behaviour:
CHANGEME Tell us what happens.

Expected behaviour Please include links to your source (for ex. wowhead.com):
CHANGEME Tell us what should happen instead.

Steps to reproduce the problem:
1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.
2. Step 2
3. Step 3

Useful links (ex; youtube.com):

**Comment by yeetmaster52** [comment]
it seems to be along some of the road as you go on to

**Comment by ForsenGM** [comment]
I advise you report the issue once again, using the correct form. This will be most likely marked as "insufficient information".
Forsen

**Comment by Zvertk69** [comment]
This seems very un-informative, I would like to see more information on future issues as so I could at least confirm this bug.

-Frost

**Comment by RenegadeWoW-CrazyJ** [comment]
Thanks for the report, but please edit this report to provide more information.
