### ISSUE TITLE
Stratholme - Timmy The Cruel

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#211]
Description:
Does not incorporate trash into his auto attacks
The ability 'Trash' is not present.  Ravenous Claw and Enrage and other scripting mechanics work properly.
'Trash: Adds a chance to do two additional attacks'

Useful links (ex; youtube.com): 
Wotlk Database: https://wotlk.evowow.com/?npc=10808
My Twitch Vod Reference: https://www.twitch.tv/videos/266166030?t=35m40s

**Comment by Cillez** [comment]
Resolved.
