### ISSUE TITLE
Core/Scripts - Stratholme - Grand Crusader Dathrohan/Balnazzar

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#213]
Description:
Its like the phase transition was just changing the character model to Balnazzar and resetting health.
DOES NOT DROP LOOT!!!

--Overall:
-When Grand Crusader Dathrohan resets/wipes the group he looses that 30% health/damage buff 
Before: https://www.twitch.tv/videos/266166030?t=1h37m06s
After: https://www.twitch.tv/videos/266166030?t=1h38m14s

--Phase 1:
-Holy Strike:  Could not tell if the ability was present or not.  (its an auto attack enhancer that does holy damage, and benifits from Crusader Strike)

--Transition Phase:  (40% health) (lasts like 2 seconds)
-Only regains health, does not get a new health pool/mana pool
-No Emotes
-Does not knock everyone down
-Immediately start auto attacking

--Phase 2:
-Does not cast 'Domination' (15s undespellable mind control)

--Database References 
Overall strategy and abilities: https://wow.gamepedia.com/Balnazzar_(original)
Grand Crusader Dathrohan: https://wotlk.evowow.com/?npc=10812
Balnazzar: https://wotlk.evowow.com/?npc=10813

--Video References
My Twitch Vod: https://www.twitch.tv/videos/266166030?t=1h37m09s
Vannila fight: https://www.youtube.com/watch?v=F_tsPlKS9U4
Vanilla fight2: https://www.youtube.com/watch?v=dOskUlfMOd0

**Comment by RenegadeWoW-CrazyJ** [comment]
Loot table will be added correctly. The Dmg/HP buff issues will be fixed core wide in a future update. Holy strike is present in testing, but "Domination" has been added to his table on a rand timer like the previous MC spell. His transition has been fixed, and will function as it should minus the emote.
The fixes will be applied with the next build.
