### ISSUE TITLE
Family Fishing pole repeat

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#22]
Zone: Darkshore
Area: Auberdine
Location: 36, 44
NPC: Gubber Blump
Quest: The Family and the Fishing Pole - 1141
Error: Once turned in, quest did not update as complete in quest log, but allowed me to pick up next quest in chain (Fruit of the sea - 1138) which is also in my quest log.

**Comment by renegadewow** [comment]
Resolved
