### ISSUE TITLE
Warlocks and Pallys get mount at 20

### ISSUE THREAD

**Issue by HeathcliffWoW** [renegadewow/Renegade-WoW#225]
Description:
Warlocks and Pallys can get the quest for their mounts at level 20 while other classes have to wait until 40 to get their mount

Current behaviour:
^^

Expected behaviour Please include links to your source (for ex. wowhead.com):
Mounts were changed to 40/60 on the server, we just need to change the quests to level 60

Steps to reproduce the problem:
1. Make Warlock
2. Level to 20
3. Talk to trainer
4. Get quest

Useful links (ex; youtube.com):

**Comment by renegadewow** [comment]
solved
