### ISSUE TITLE
Gahz'rilla

### ISSUE THREAD

**Issue by Qvistt** [renegadewow/Renegade-WoW#227]
Description:
Last boss in Zul'Farak ''Gahz'rilla'' not attackable after hitting gong.

Current behaviour:
After hitting gong to spawn Gahz'rilla, he spawns as intended but goes down the water and seem to attack something invisible forever and becomes unattackable.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Gah'rilla is supposed to spawn when hitting the gong(as he does)then walk up from the water and become attackable.
Steps to reproduce the problem:
1. Find out what invisible creature he seem to be attacking.
2. Remove said creature.
3. =Profit. xd

https://imgur.com/a/KQwsyka

**Comment by Cillez** [comment]
Added a double check to his immunity after reaching WP. Was unable to reproduce bug tho, so it shouldn't happend again if it's a once in a while thing. Thanks for your contribution. Fix applied to main realm already
