### ISSUE TITLE
mobs despawn way to fast

### ISSUE THREAD

**Issue by rawseki** [renegadewow/Renegade-WoW#229]
Description:
Corpses always despawn very fast. sometimes cannot loot or skin.

Current behaviour:
CHANGEME Tell us what happens.

Expected behaviour Please include links to your source (for ex. wowhead.com):
CHANGEME Tell us what should happen instead.

Steps to reproduce the problem:
1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.
2. Step 2
3. Step 3

Useful links (ex; youtube.com):

**Comment by HeathcliffWoW** [comment]
The corpse despawn rate is set to normal levels, with most mobs despawning 5 minutes after they have been looted.  The exception to this is spawned adds during boss fights, those despawn once the boss that summoned them is dead
