### ISSUE TITLE
Quest chain problems - BuzzBox 827

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#23]
Zone: Darkshore
Area: Auberdine
Location: 36, 46
Quest: Buzzbox 827 - 983
Error: Once complete and turned in, NPC dialogue box doesn't close once "Complete Quest" is clicked.  To bypass, click on "X" (top right corner of dialogue box) or stepping away to proceed.

This problem is relevant on several quest chains.

**Comment by Cillez** [comment]
Resolved.
