### ISSUE TITLE
Can't learn Rockbiter rank 5 and up

### ISSUE THREAD

**Issue by Lindariel** [renegadewow/Renegade-WoW#233]
Description:
Tried every single trainer Alliance And Horde, I can't learn any Rank above 4 of Rockbiter

Current behaviour:
Missing from trainers for some reason.

Expected behaviour Please include links to your source (for ex. wowhead.com):
https://tbc-twinhead.twinstar.cz/?spell=10399
there should be more than 4 ranks available in vanilla.

Steps to reproduce the problem:
Just go to a trainer and see

**Comment by Cillez** [comment]
You have to check wotlk databases as this is wotlk emulating vanilla. I did check the wotlk databases, and all say there are only 4 ranks. 

Reopen if im mistaken.
