### ISSUE TITLE
Mobs @ Echo Isles (raptors, tigers) will deaggro and tether back if you jump in water.

### ISSUE THREAD

**Issue by doom2099** [renegadewow/Renegade-WoW#26]
Description:
CHANGEME Description of the problem or issue here.

Current behaviour:
CHANGEME Tell us what happens.

Expected behaviour Please include links to your source (for ex. wowhead.com):
CHANGEME Tell us what should happen instead.

Steps to reproduce the problem:
1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.
2. Step 2
3. Step 3

Useful links (ex; youtube.com):

**Comment by miteegrimm** [comment]
Zone: Durotar
Area: Echoe Isles
Location: Around 65,83 (and surrounding islands)
Mobs: Durotar Tiger, Bloodtalon Taillasher (There are trolls on the islands but their kite range doesn't extend to the water.

Error: Durotar Tiger and Bloodtalon Taillasher can be aggroed and will drop agro instantly once the player begins swimming.  This is a minor bug.

**Comment by renegadewow** [comment]
Resolved
