### ISSUE TITLE
Plainstiders @ The Barrens have a massive loot table

### ISSUE THREAD

**Issue by doom2099** [renegadewow/Renegade-WoW#27]
Description:
Plainstiders @ The Barrens have a massive loot table

Current behaviour:
Plainstriders drop like 8-9 items at once

Expected behaviour Please include links to your source (for ex. wowhead.com):
CHANGEME Tell us what should happen instead. Lower loot table

Steps to reproduce the problem:
1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.
2. Step 2
3. Step 3

Useful links (ex; youtube.com):

**Comment by miteegrimm** [comment]
Zone: The Barrens
Area: The Barrens
Location: 50, 30
Mob: Greater Plainstriders
Error: The whole loot table appears per kill. (Minor bug, fine tuning server drop rates should correct.)

**Comment by Cillez** [comment]
Resolved.
