### ISSUE TITLE
Purple raptors outside of Crossroads not moving/sitting in one spot.

### ISSUE THREAD

**Issue by doom2099** [renegadewow/Renegade-WoW#28]
Description:
Purple raptors outside of Crossroads not moving/sitting in one spot.

Current behaviour:
Purple raptors outside of Crossroads not moving/sitting in one spot.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Moving/Patrolling around.

**Comment by miteegrimm** [comment]
Zone: The Barrens
Area: The Barrens (Outside of The Crossroads)
Location (of all mobs): 52, 33 (X3) - 50, 31
Mob: Sunscale Lashtail, Gazelle (51, 32)
Error: These mobs are standing in place, no roaming or pathing.
May try reloading DB or server restart to correct.

**Comment by renegadewow** [comment]
Resolved
