### ISSUE TITLE
Teacher and Students in Storwind not pathing in order

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#29]
Zone: Stormwind
Area: Stormwind
Location: Generalized
NPC's:
Miss Dana
Steven
Twain
Pat
Jimmy
Mikey
Andi

Error: The NPC's are pathing in correct regions, only the students are out of sync with the teacher "Miss Dana".  The teacher should be within their group only slightly ahead of them.

**Comment by renegadewow** [comment]
Seems to be Resolved
