### ISSUE TITLE
Dwarf excavation site @ South Barrens

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#34]
Zone: Barrens
Area: Bael Modan
Location: 47, 85 (large area) and 48, 84 (small area and inside building)
Mobs: 
In large area
Bael'dun Foreman
Bae'dun Excavator
Digger Flameforge
Prospector Khazgorm
Lord Cyrik Blackforge
Heggin Stonewhisker

In smaller area and building
Bael'dun Soldier
Bael'dun Rifleman
Bael'dun Officer
General Twinbraid (lowest floor)

Error: These mobs are not pathing at all.

**Comment by Cillez** [comment]
Fixed NPC's on the highest lvls. Seeing if i can port them over to the rest.

**Comment by Cillez** [comment]
Resolved.
