### ISSUE TITLE
Defias Thug & Other not aggro

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#36]
Zone: Elwynn Forest
Area: Northshire Vineyards
NPCs: Defias Thug & Garrick Padfoot
Error: These mobs should be aggressinve.
Information: Before applying fix, check area as it may be overpopulated with spawns.
https://classicdb.ch/?npc=38
https://classicdb.ch/?npc=103

**Comment by renegadewow** [comment]
Resolved
