### ISSUE TITLE
Bloodscalp Mystic

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#37]
Zone: Stranglethorn Vale
Area: Ruins of Zul'Kunda
Area: 25, 9
Mob: Bloodscalp Mystic
Ability: "Throw"
Errors:
1) "Throw" is done without an animation.
2) "Throw" has no minimum range (5meters/melee range).
3) Mob spams "Throw" constantly, only to pause and use "Quick Flame Ward".
4) "Enrage" should be cast at combat start.
5) Mob fails to cast "Lightning Bolt".

**Comment by Cillez** [comment]
Resolved.
