### ISSUE TITLE
Darkmoon Fair sells lvl 70 equip

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#39]
Darkmoon Fair Event
NPCs:
Lhara
Professor Thaddeus Paleo
Stamp Thunderhorn
Sylannia

Errors:
Lhara sells tbc and wrath materials
Professor Thaddeus Paleo Sells level 70 scrolls
Stamp Thunderhorn sells level 65 food
Sylannia sells level 60&70 water

**Comment by Cillez** [comment]
@miteegrimm Which items should be removed from Lhara?
Not worth removing level 61+ items, they can't be used until you reach required level, and would need to be re added when we progress to TBC.

**Comment by siscostrife** [comment]
the motes and eternals

**Comment by siscostrife** [comment]
at the very least

**Comment by Cillez** [comment]
resolved.
