### ISSUE TITLE
Nelf Gnarlpine Mobs 

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#4]
Zone: Teldrassil
Areas: Ban'ethil Hollow (44, 55) and Teldrassil (general area mobs in question, can be found at 50, 62)
Mobs: Gnarlpine Defender, Gnarlpine Shaman, Gnarlpine Ambusher, Gnarlpine Augur
Error: Neither mobs flee when low on health.
Error: Gnarlpine Shaman's mana regenerates in combat too quickly.
Error Gnarlpine Shaman uses "Healing Wave" too often during combat in some cases. (Tried at Ban'ethil Barrow Den 44, 60)

http://www.wowhead.com/npc=2009/gnarlpine-shaman#abilities

**Comment by miteegrimm** [comment]
leave open, will post comment when finished testing of the gnarlpine mobs

**Comment by renegadewow** [comment]
Update# Creatures now flee when low on health.

**Comment by miteegrimm** [comment]
I'm Ok with closing

**Comment by Cillez** [comment]
Resolved.
