### ISSUE TITLE
Grimlok in Northshire

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#42]
Zone: Elwynn Forest
Area: Northshire Valley
Location: 47.05, 47.88
Mob: Grimlok
GUID: 1977671
NPC ID: 4854
NPC DispayID: 11165

Error: This mob spawns at the gates to Northshire Valley and is killed by the Northshire Guard.  Grimlok is only referenced as an Uldaman boss.

https://classicdb.ch/?npc=4854#comments

**Comment by Cillez** [comment]
Resolved
