### ISSUE TITLE
Princess - Elwynn Forest

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#45]
Zone: Elwynn Forest
Area: Brackwell Pumpkin Patch
Location: 69.69, 79.04
Mobs: Princess (80849), Porcine Entourage (80850) (80848)
Error: Princess should path around the insides of the pumpkin patch, escorted by her two body guards (Porcine Entourage).
http://wowwiki.wikia.com/wiki/Quest:Princess_Must_Die!

**Comment by Cillez** [comment]
Resolved.
