### ISSUE TITLE
Defias Pillager - LOS problem

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#48]
Zone: Westfall
Area: Moonbrook
Location: 71, 48
Mob: Defias Pillager
Error: When line of sighting this mob, it will not run towards the player, rather it will path around the corner to continue casting.

Recommend taking a look at a few other casters to see if this is a common bug.

**Comment by Cillez** [comment]
Will be fixed via overall patching of creatures in c++
