### ISSUE TITLE
Foror's Compendium of Dragon Slaying - Accuracy of DB check for drop rate

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#49]
Item: Foror's Compendium of Dragon Slaying
ItemID: 18401
Used to start quest: "The Forging of Quel'Serrar" (7508 & 7509)
Item: Quel'Serrar (18348) is the end result of the quest chain to be turned in at Dire Maul

10% drop rate (highest rated drop chance on mob) by "Guard Slip'kik" (14323)

https://classicdb.ch/?item=18401

**Comment by Cillez** [comment]
Not clear to me what the bug is

@miteegrimm ?

**Comment by Cillez** [comment]
Resolved.
