### ISSUE TITLE
Baron Rivendare - "debuff" and yells

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#51]
Zone: Eastern Plaguelands
Area: Stratholm
MOB: Baron Rivendare

Error: 
Once Baron Rivendare is defeated, the debuff "The Baron's Ultimatum" and his yells continue.  The debuff should dissipate and the yells should cease.

**Comment by Cillez** [comment]
Resolved. Tested solo, might need futher testing.
