### ISSUE TITLE
Scholomance - Pathing

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#52]
Zone: Eastern Plaguelands
Area: Scholomance
Location: Whole Instance
Quest(s):
Mob/NPC/Item/WorldItem/Spell/Ability:
Description: Walking through walls, float in the air, basically no waypoints assigned to them
Resources: Retail experience
https://user-images.githubusercontent.com/37052729/37115514-9bdf1748-224b-11e8-8c9e-ed172ede5c10.png

**Comment by Cillez** [comment]
This is the case for many, if not all instances. once we find a fix, all these issues will disappear. Closing.

**Comment by Cillez** [comment]
Fixed in all instances. Tested and working properly.
