### ISSUE TITLE
Scholomance - Mob group pulls

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#53]
Zone: Eastern Plaguelands
Area: Scholomance (Inside instance)
Mobs: Necrofiend and Necrolyte / Scarlet Crusade (any within Scholomance)
Error:
1) When a Necrofiend or a Necrolyte is pulled, the group they are standing with do not aggro with them.  Any mob not pulled directly via taunt or ranged attack will instead continue their out of combat gossip.
2) You can split pull mobs from their respective packs.  Also some flaws in LOS pathing. I.E walking through walls.

https://user-images.githubusercontent.com/37052729/37117446-868a641e-2251-11e8-8080-e3659b9349e1.png

**Comment by renegadewow** [comment]
Resolved
