### ISSUE TITLE
Risen Aberration immunities are reversed

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#54]
Zone: Eastern Plaguelands
Area: Scholomance
Location: Scholomance
Mob: Risen Aberration
Description: Immune to Holy Spell School. They should be Immune to all Spell Schools except Holy.

https://user-images.githubusercontent.com/37052729/37118762-97640cd2-2255-11e8-8b6d-51c8d2a56b72.jpg

https://wow.gamepedia.com/Risen_Aberration

**Comment by Cillez** [comment]
Resolved.
