### ISSUE TITLE
Balnazzar spawns out of default parameters.

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#55]
Zone: Eastern Plaguelands
Area: Stratholme Live
Location: Right after the double gates event
Mob: Balnazzar
Error: Balnazzar spawns right outside of the double gate event in Stratholme live.  He is end boss of Stratholme live.

https://user-images.githubusercontent.com/37052729/37123755-9f11b9a6-2265-11e8-9beb-84ef044de08d.png

https://wow.gamepedia.com/Balnazzar_(original)

**Comment by miteegrimm** [comment]
Additionally, ensure Balnazzar is immune to "Fear" and "Stun" mechanics.

**Comment by Cillez** [comment]
Npc removed, now only spawned at correct location.
