### ISSUE TITLE
Scarshield Warlock casting error

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#57]
Zone: Burning Steppes
Area: Lower Blackrock Spire
Mob: Scarshield Warlock
Description: Warlock is casting the summon spell, the summon spell is following warlock around and doesn't spawn any mobs. The Scarshield Warlock should stand still and spawn mobs.
Resources: https://vanilla-twinhead.twinstar.cz/?spell=15125

**Comment by Cillez** [comment]
Casting the spell like it should. Problem is the spell itself not working properly.

**Comment by renegadewow** [comment]
Need to Fix following issue

**Comment by renegadewow** [comment]
Resolved 100%
