### ISSUE TITLE
Quest - The Hunter's Path 

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#58]
Zone: Durotar
Area: Razor Hill
Location: 51.85, 43.45
Quest: The Hunter's Path
NPC: Thotar
Description: Thotar has the quest "The Hunter's Path," which tells you to talk to Thotar in Razor Hill...  Which you are already doing. 
Error: Can obtain the quest from the NPC while currently on said quest from another NPC.
Resources: http://www.wowhead.com/quest=6070/the-hunters-path

**Comment by miteegrimm** [comment]
According to original ticket, this quest might be picked up in two other locations.  Will need to do some looking to verify, but I believe this quest as all other class quests become available at all class trainers to ensure travel to a specific area for class quest chains or ability/spell unlocks.

**Comment by Cillez** [comment]
Resolved.
