### ISSUE TITLE
Mosh'Ogg Witch Doctor totem moving

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#59]
Zone: Stranglethorn Vale
Area: Mizjah Ruins
Location: 46, 53 (area)
Mob: Mosh'Ogg Witch Doctor
Spell: Ward of Laze
Error:  Mob's summoned totem moves around and follows the mob if he moves in any direction. Totem should be stationary.

https://user-images.githubusercontent.com/37053064/37133326-484cd810-2258-11e8-99ab-0df9262ef6a8.png

http://www.wowhead.com/npc=1144/moshogg-witch-doctor#abilities

**Comment by Cillez** [comment]
Resolved
