### ISSUE TITLE
Upper Blackrock Spire - Door into 1st boss

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#60]
Current behaviour:
Door into First boss is open without killing any of the groups in Dragonspire Hall

Expected behaviour Please include links to your source (for ex. wowhead.com):
Door should be closed and only open after you kill packs in each cubby in Dragonspire Hall

![image](https://user-images.githubusercontent.com/37052729/37155287-cd22bbf6-22e2-11e8-9c34-2c275070f856.png)

**Comment by renegadewow** [comment]
Resolved
