### ISSUE TITLE
Upper Blackrock Spire - Rend's event

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#61]
Current behaviour:
When you jump down, Neff starts to say his lines and the event starts. The door into Blackrock Stadium does not close and the gate opens and closes after 6 sec. It does spawn first wave and thats it. When Neff tells Rend to get there, nothing happens.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Door into Blackrock Stadium should be closed when Event starts and there should be waves spawning until Rend comes riding on Gyth.

https://www.youtube.com/watch?v=rQB_YLeaTIc

**Comment by Cillez** [comment]
Door into blackrock stadium is closed now. 
The phases still doesn't spawn.
Gyth spawns correctly and walks to the middle, while Rend is mounted on Gyth.

TODO:
Find a way to spawn the rest of the waves
Fix pathing for all waves.

**Comment by RenegadeWoW-CrazyJ** [comment]
The encounter has been fixed and will be applied during the next restart.
