### ISSUE TITLE
Upper Blackrock Spire - The Beast

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#62]
Description:
The Beast mechanics are not working at all

Current behaviour:
he just a 80k hp punching bag

Expected behaviour Please include links to your source (for ex. wowhead.com):
He is suppose to cast fireballs, do aoe fear and fire nova.

https://www.youtube.com/watch?v=Ms8M8MFLYXw

**Comment by Cillez** [comment]
Working on next core update (Not server restart)
