### ISSUE TITLE
Upper Blackrock Spire - Solakar Flamewreath

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#63]
Description:
Father Flame event didn't start after you collected that item from pillar

Current behaviour:
No waves of drakeoids

Expected behaviour Please include links to your source (for ex. wowhead.com):
Waves of Drakes until Solakar Flamewreath spawns. 

http://wowwiki.wikia.com/wiki/Solakar_Flamewreath

**Comment by RenegadeWoW-CrazyJ** [comment]
This encounter has been scripted, and will available with our next build. Note: The Father Flame item will be a 100% drop from Solakar instead of from the stone itself.
