### ISSUE TITLE
Blackrock Depths: Golem Lord Argelmach 

### ISSUE THREAD

**Issue by siscostrife** [renegadewow/Renegade-WoW#67]
Description:
Golem Lord Argelmach doesnt activate golems to aid him in the fight
Golem names: Wrath Hammer Construct, Ragereaver Golem

Current behaviour:
Boss fights alone adds dont trigger

Expected behaviour Adds should begin attacking with boss
https://www.youtube.com/watch?v=z5whWPFQ8yE

Steps to reproduce the problem:
1. Step 1 attack boss

Useful links (ex; youtube.com):  full fight https://www.youtube.com/watch?v=z5whWPFQ8yE

**Comment by renegadewow** [comment]
Resolved
