### ISSUE TITLE
Undercity list of characters above level 60

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#70]
Kor'kron Overseer - lvl 75
Steamwheedle Bruiser - lvl 75
Royal Dreadguard - lvl 80
Deathguard Elite - lvl 75

Dark Ranger Anya - lvl 80
Dark Ranger Clea - "
Dark Ranger Cyndia - "
Bragor Bloodfist - lvl 80
Aleric Hawkins - lvl 80
Sarah Forthright - lvl 80
Overseer Kraggosh - lvl 75
Walter Soref - lvl 75
Lyrlia Blackshield lvl 71
Rex Pixem - lvl 70
Michael Garrett - lvl 65

Or just look at this list and organize by level.  https://wotlk.evowow.com/?zone=1497#npcs:0-2+1

**Comment by dreadnought101** [comment]
Same with other cities, also the faction bosses themselves are probably using wrath mechanics but I honestly dont recall how SKULL level mechanics work for wotlk

**Comment by Cillez** [comment]
Resolved. Fix will soon be implemented to PTR live.
