### ISSUE TITLE
Mage Flamestrike - additional ticks crit, cause Ignite

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#78]
Flamestrike initial strike can crit/cause ignite as normal

However after the initial hit, the aoe on the ground ticks can crit (not blizzlike) and can cause ignite (even worse)

tested other over time affects including Pyroblast, Fireball, Living Bomb, Ignite itself, do not crit+cause ignite

**Comment by Cillez** [comment]
Confirmed.

**Comment by dreadnought101** [comment]
You are correct in that the initial strike of flamestrike should benifit from talents, however its DOT affects afterwards are ALSO benefiting from talents, which should not be the case.

**Comment by Cillez** [comment]
resolved.
