### ISSUE TITLE
Denalan's Planter

### ISSUE THREAD

**Issue by miteegrimm** [renegadewow/Renegade-WoW#8]
Zone: Teldrassil
Area: Lake Al'Ameth
Location: 60, 68
Item: Denalan's Planter
Quest: Denalan's Earth
Information: Quest requires you to speak with Denalan, which will take the "Rare Earth" quest item from you to complete the quest.
Error: During and after quest, you can right click on Denalan's Planter, which will bring up NPC dialog box.  Repeatable.
http://www.wowhead.com/quest=997/denalans-earth

**Comment by Cillez** [comment]
Resolved.
