### ISSUE TITLE
DM East - Few bugs

### ISSUE THREAD

**Issue by TheFatMike** [renegadewow/Renegade-WoW#80]
Description:
There are a few bugs i would like to report about DM, first of all the Warpwood crusher in DM East on the right as soon as you get in can get stuck up on the pillar http://prntscr.com/j8y7d1 this is a picture to show what happens, 2nd of all the doors are already open inside the dungeon no need to speak to npc's etc and finally the bosses don't pull any rooms this makes it really easy to skip mobs and just go for last boss also 1 last thing all bosses in DM can be stun locked.

Current behaviour:
Warpwood crusher getting stuck, bosses not pulling mobs and doors being open.

Expected behaviour Please include links to your source (for ex. wowhead.com):
I don't know how to include links from wowhead.com on my problems due to no information in wowhead. If you would like more information about this i am FatMike on discord please contact me on there.

Steps to reproduce the problem:
On the Warpwood crusher if you use a range attack to pull him, he will walk up onto the pillar.

**Comment by BanjeeWoW** [comment]
Additionally worth noting is that all Bosses are stunnable in DM:E that we killed (Didnt do Lethtendris, seems likely that she is too tho) This also Applies to the 3 Guards in DM:N and Stomper Kreeg. Didnt get to test Krom'Krush and the King however again it seems likely that they are too and it wouldnt hurt looking at them too.

**Comment by Cillez** [comment]
Issue in comments has been taken care of, issue #82

**Comment by PrinceMonsterTruck** [comment]
So I did some investigating, and the Guards able to be stunned is a Blizzlike feature (I ran it last night on live)

**Comment by Cillez** [comment]
resolved.
