### ISSUE TITLE
Hall of blackhand

### ISSUE THREAD

**Issue by TheFatMike** [renegadewow/Renegade-WoW#81]
Description:
In the hall of blackhand if you pull mobs in a corridor and walk backwards the mobs start to float http://prntscr.com/j8zssh this is a picture of them floating in the roof you can just about see their feet.

Current behaviour:
If you attack a mob range and move backwards they float into the roof.

Expected behaviour Please include links to your source (for ex. wowhead.com):
They are supposed to stay on the floor.

Steps to reproduce the problem:
Attack mobs at range and move back.

**Comment by Cillez** [comment]
Resolved, should be working correctly on next restart.
