### ISSUE TITLE
Warpwood Pod (object=179526)

### ISSUE THREAD

**Issue by Kentamentiu** [renegadewow/Renegade-WoW#82]
Description:
When opening a Warpwood Pod, nothing happens, you can simply collect the loot and move on.

Current behaviour:
Acts like a lootbox that always gives the Runn Tum Tubers

Expected behaviour Please include links to your source (for ex. wowhead.com):
http://www.wowhead.com/object=179526/warpwood-pod#comments

1) Spawn little 5-6 little mobs (//www.wowhead.com/?npc=13022)
2) Poisons you (a nature DoT)
3) Yields either Runn Tum Tuber (//www.wowhead.com/?item=18255), used in the recipe Runn Tum Tuber Surprise (//www.wowhead.com/?spell=22761) and/or Thornling Seeds (//www.wowhead.com/?item=18297)
4) Does nothing at all

Steps to reproduce the problem:
1. Go to Dire Maul East and click one of the Warpwood Pods
2. observe

**Comment by BanjeeWoW** [comment]
Earlier Today, when we did DM:East Warpwood pods also constantly spawned
"Warpwood Spores" when you stand on top of them. Warpwood spores are lvl 1 mobs, agressive. They also have no Model at all and seemed to spawn endlessly.

**Comment by Cillez** [comment]
https://github.com/TrinityCore/TrinityCore/issues/19257
