### ISSUE TITLE
Rares spawning in dungeon 100% of the time

### ISSUE THREAD

**Issue by TheFatMike** [renegadewow/Renegade-WoW#83]
Description:
In every dungeon i have done Rare mobs are spawning 100% of them so they are not really rare.

Current behaviour:
Rares spawning 100% of the time. This is a picture of the wailing caverns one http://prntscr.com/j97mgk

**Comment by PrinceMonsterTruck** [comment]
This sounds like the Rare mobs aren't correctly pooled, thus ignoring the chance of spawning and just always being there

**Comment by Cillez** [comment]
Resolved.
