### ISSUE TITLE
Stunnable Dungeon Bosses

### ISSUE THREAD

**Issue by BanjeeWoW** [renegadewow/Renegade-WoW#84]
Description:
Every single Boss i have come across so far was stunnable. This includes Hydrospawn, Zevrim Thornhoof, Isalien, Alzzin The Wildshaper in DM:E aswell as all 3 Guards in DM:N 
The rest of the Bosses in those dungeons we didnt test, i wouldnt expect them to work different tho

Current behaviour:
Using Stuns on any of the Mentioned Bosses Stuns them ( Tested Abilities are Cheap Shot, Kidney Shot and Hammer of Justice)

Expected behaviour:
Stunning  a boss should not work, they should be immune

Steps to reproduce the problem:
Use a stun on a Boss, duh

**Comment by Cillez** [comment]
Bosses are now immune to stuns.
