### ISSUE TITLE
Mobs in Orc/Troll starting zone are not agressive

### ISSUE THREAD

**Issue by TheFatMike** [renegadewow/Renegade-WoW#87]
Description:
The mobs inside orc or troll starting zones are not aggressive even in the cave with the familiars and felstalkers

Current behaviour:
Non are aggressive.

Expected behaviour Please include links to your source (for ex. wowhead.com):
The Mobs inside the cave should be aggressive.

I have put a screen shot with an arrow to the cave http://prntscr.com/j9xwm5

**Comment by Cillez** [comment]
Resolved
