### ISSUE TITLE
Mobs at Brambleblade Ravine (tauren starting zone) not agressive

### ISSUE THREAD

**Issue by TheFatMike** [renegadewow/Renegade-WoW#89]
Description:
Bristleback Quilboar, Bristleback Shaman, Bristleback Battleboar and Chief Sharptusk Thornmantle are not agressive.

Expected behaviour Please include links to your source (for ex. wowhead.com):
Should be aggressive

Here is a link to where on the map http://prntscr.com/ja6m3b

**Comment by Cillez** [comment]
Resolved.
