### ISSUE TITLE
Mobs in starting zone not aggressive

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#90]
**These mobs do not attack you when you are next to them**  Passive vs Aggressive bug

**Dwarf/Gnome Starting Zone**
Frostmane Troll Whelp
Frostmane Troll Novice
Grik'nir the Cold

**Night Elf Starting Zone**
Webwood Spider
Githyiss the Vile

**Draenei Starting Zone**
Blood elf Scout
Surveyor Candress

**Undead Starting Zone**
Young Night Web Spider
Night Web Matriarch

**Blood Elf Starting Zone**
Arcane Wraith
Tainted Arcane Wraith
Felendren the Banished

**Comment by Cillez** [comment]
Resolved.
