### ISSUE TITLE
Lvl 10 Hunter Pet Quest

### ISSUE THREAD

**Issue by Jawul** [renegadewow/Renegade-WoW#92]
You cant Dissmiss the Pets you need to Tame for the quest!
Also the Tamed Pets for the Quest doesnt follow the hunter

**Comment by Cillez** [comment]
Assuming this is regarding Quest:Taming the Beast. 

Tested the quest. first issue might've been a weird bug at the time, as it is working fine now.
It is also following correctly when i tame Webwood Lurker, which is one of the mobs to tame when doing the quests. 

Not sure if this report is for another quest than the one i assumed it is.

No enough information. Follow template next time.

@Jawul  Care to confirm if it is Taming the Beast you are talking about?

**Comment by PrinceMonsterTruck** [comment]
The cause of this bug has to do with the way the server handles "Tamed" creatures.  The same effect happens with Mind Control.  Once the "Tame" is complete, the NPC will no longer attack, do anything besides patrol around until they are Killed, or manually respawned

**Comment by Cillez** [comment]
Resolved.
