### ISSUE TITLE
Trauma [Warrior Talent Arms]

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#93]
It doesn't not apply as debuff, but rather as buff on mobs and players. Can be removed by the player.

It is suppose to be a debuff, which renews everytime you crit.

![image](https://user-images.githubusercontent.com/37052729/39473307-846e0b90-4d4e-11e8-8687-9aa2ac189a8c.png)

**Comment by Cillez** [comment]
Resolved.

**Comment by Juckiey** [comment]
This applies to more than just trauma, though i dont have a list of class or npc debuffs that have this problem. Could maybe have someone go through the class debuffs during beta and make that list. But i reckon on live, players will eventually get to reporting the npc debuffs they notice as buffs during play

**Comment by Cillez** [comment]
The fix applied to fix Trauma, will work for most, if not all other spells that had that issue.
