### ISSUE TITLE
Auto shoot while Volley

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#94]
You can auto shoot while using hunter aoe ability Volley.

Expected behaviour Please include links to your source (for ex. wowhead.com):
You can't auto shoot while volley because it is a channelling spell and it stops auto shoot to go off until it is done channelling.

Steps to reproduce the problem:
Apply auto shoot on any target and use volley you will see white hits with yellow volley hits.

![image](https://user-images.githubusercontent.com/37052729/39473457-457ea916-4d4f-11e8-8307-277ad661fa9c.png)

**Comment by RenegadeWoW-CrazyJ** [comment]
Need source on blizzlike functionality, as autoshot is meant to work during the casting of some spells (Steady Shot).

**Comment by Cillez** [comment]
Been watching a few videos of this, was unable to find anything until i got to legion, where autoshot is supposed to happen during volley. I know myself that there are huge differences between legion and wotlk, but without posting a source (which is asked for when creating a bug report) we will close this issue until proof/source is provided.
