### ISSUE TITLE
Stormstrike [Enhancement Shaman Talent]

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#96]
It doesn't show up as Debuff on target, can be removeable (click away, macro /cancelaura) by player.

It is suppose to be a debuff, not a buff.

![image](https://user-images.githubusercontent.com/37052729/39474771-dbe9ecca-4d55-11e8-91bf-7530226d0dc5.png)

**Comment by Cillez** [comment]
Resolved.
