### ISSUE TITLE
Mangle [Feral Druid Talent]

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#97]
It is showing up as buff on target, can also be removable by target.

Suppose to be a debuff on target.

![image](https://user-images.githubusercontent.com/37052729/39475046-f1c57540-4d56-11e8-9772-6d7a040a607a.png)

**Comment by PrinceMonsterTruck** [comment]
Affected spell Id is 33982, Looking into it

**Comment by Cillez** [comment]
Resolved.
