### ISSUE TITLE
[Mage] Clearcasting Buff lingers (visual)

### ISSUE THREAD

**Issue by Kentamentiu** [renegadewow/Renegade-WoW#99]
Description:
When spamming spells, the Buff Clearcasting sometimes remains visible in the buff bar (without addons), despite being already used.
This is only a visual bug, since the effect no longer works. Only the buff icon with its timer is still visible

Current behaviour:
This only occurs when spamming spells and using the latency queueing system. 

Expected behaviour Please include links to your source (for ex. wowhead.com):
The buff icon should disappear, even when chainspamming spells.

Steps to reproduce the problem:
1. Spec into Arcane Concentration 
https://wotlk.evowow.com/?spell=12577

2. Spam spells without delay.

3. observe your buff bar.

**Comment by Animalthug** [comment]
Can't reproduce, can't confirm.

**Comment by Cillez** [comment]
Also unable to reproduce this issue.

**Comment by renegadewow** [comment]
Couldn't reproduce.
